### PR TITLE
cbe: update singularity version

### PR DESCRIPTION
**Pull request by phue**
singularity/3.1.0 is not available anymore

### CODE REVIEW

**Comment by drpatelh** [comment]
Hope you're well @phue !! Feel free to merge when the tests pass :+1:

**Comment by phue** [comment]
That was quick. Thanks :smile:

**Comment by apeltzer** [comment]
Wow you drop singularity versions quickly - we’re still on 3.0.3 😱

**Comment by phue** [comment]
This is the reason it was dropped:
https://cve.mitre.org/cgi-bin/cvename.cgi?name=2019-11328

**Pull request merged**
