### PR TITLE
Addition of ATAC-seq pipeline config, updated docs

### PR DESCRIPTION
**Pull request by ameynert**
* Added more GATK dependent processes to eddie Sarek pipeline config with Java memory overhead specification
* Added ATAC-seq pipeline eddie config
* Updated eddie documentation to reflect use of shared Singularity cache rather than one per pipeline/version combination

### CODE REVIEW

**Comment by MaxUlysse** [comment]
Institutional pipeline specific configs is not yet available for atacseq, but should be available soon

**Comment by ameynert** [comment]
Is it alright to commit the ATAC-seq config or shall I take it out?

**Comment by ameynert** [comment]
I've taken out the ATAC-seq pipeline-specific config.

**Review by jfy133 — APPROVED** [review]
Lgtm!

**Pull request merged**
