### PR TITLE
leicester config improved

### PR DESCRIPTION
**Pull request by maxozo**
---
name: New Config
about: A new cluster config
---

Please follow these steps before submitting your PR:

- [x] If your PR is a work in progress, include `[WIP]` in its title
- [x] Your PR targets the `master` branch
- [x] You've included links to relevant issues, if any

Steps for adding a new config profile:

- [x] Add your custom config file to the `conf/` directory
- [x] Add your documentation file to the `docs/` directory
- [x] Add your custom profile to the `nfcore_custom.config` file in the top-level directory
- [x] Add your custom profile to the `README.md` file in the top-level directory
- [x] Add your profile name to the `profile:` scope in `.github/workflows/main.yml`

### CODE REVIEW

**Comment by maxozo** [comment]
> What is this ` Submodule configs added at 08bfa2`?

I am not sure, but thats not needed. I can not see any submodules folder anywhere.

**Comment by maxulysse** [comment]
> > What is this ` Submodule configs added at 08bfa2`?
> 
> I am not sure, but thats not needed. I can not see any submodules folder anywhere.

Looks like a git submodule was added in this commit: https://github.com/maxozo/configs/commit/bcdba6b4e629169da5e60a80d7afd712ef3152de

Can you remove it?

**Comment by maxozo** [comment]
> 

yes, will remove. thanks for noticing this.

**Comment by maxozo** [comment]
> What is this ` Submodule configs added at 08bfa2`?

this has been removed now.

**Review by maxulysse — APPROVED** [review]

**Comment by maxulysse** [comment]
> > 
> 
> yes, will remove. thanks for noticing this.

That's why we do reviews ;-)

**Pull request merged**
