### PR TITLE
Add University of Dundee cluster config

### PR DESCRIPTION
**Pull request by dsloanm-uodit**
---
name: New Config
about: A new cluster config
---

A workaround for https://github.com/nextflow-io/nextflow/issues/2449 is included in the config file. Following the approach at https://github.com/nf-core/configs/blob/9c4830c/conf/hebbe.config#L16-L17

Please follow these steps before submitting your PR:

- [ ] If your PR is a work in progress, include `[WIP]` in its title
- [x] Your PR targets the `master` branch
- [x] You've included links to relevant issues, if any
- [x] Requested review from @nf-core/maintainers and/or #request-review on slack

Steps for adding a new config profile:

- [x] Add your custom config file to the `conf/` directory
- [x] Add your documentation file to the `docs/` directory
- [x] Add your custom profile to the `nfcore_custom.config` file in the top-level directory
- [x] Add your custom profile to the `README.md` file in the top-level directory
- [x] Add your profile name to the `profile:` scope in `.github/workflows/main.yml`

### CODE REVIEW

**Review by jfy133 — APPROVED** [review]
Theoretically OK, however you've not specified any software environment system which is also quite important (conda, docker, singularity etc.). I see you ask people to use conda to install Nextflow itself, is that the only engine available? If so I would turn that on in the config too

**Comment by dsloanm-uodit** [comment]
Thanks for the comments - I have explicitly enabled conda in the config. Ideally we would like to use Singularity but our compute nodes aren't quite set up for it yet. It's something we're aiming for, however.

**Comment by jfy133** [comment]
One last thing to document: I would recommend users specifying a [NXF_CONDA_CACHEDIR](https://www.nextflow.io/docs/latest/config.html#environment-variables) env variable so they don't create the same conda environments for every run

**Comment by dsloanm-uodit** [comment]
I've added some notes on NXF_CONDA_CACHEDIR (and fixed a typo in a section header). Thanks again

**Comment by jfy133** [comment]
Will wait for tests to pass the nwill merge :+1:

**Pull request merged**
