### PR TITLE
Remove kraken profile

### LINKED ISSUE #229: remove kraken profile

### PR DESCRIPTION
**Pull request by maxulysse**
Will close #229

### CODE REVIEW

**Review by jfy133 — APPROVED** [review]

**Comment by maxulysse** [comment]
Thanks @jfy133 I totally forgot about this one

**Comment by jfy133** [comment]
Thank mattermost GitHub bot for telling me 😂

**Comment by maxulysse** [comment]
We should really go through all open issues/PRs repo by repo more often

**Comment by jfy133** [comment]
Maybe schedule a bi-annual  cleanup

**Pull request merged**
