### PR TITLE
New seawulf config

### PR DESCRIPTION
**Pull request by davidecarlson**
---
name: New Config
about: A new cluster config
---

Please follow these steps before submitting your PR:

- [x] If your PR is a work in progress, include `[WIP]` in its title
- [x] Your PR targets the `master` branch
- [x] You've included links to relevant issues, if any

Steps for adding a new config profile:

- [x] Add your custom config file to the `conf/` directory
- [x] Add your documentation file to the `docs/` directory
- [x] Add your custom profile to the `nfcore_custom.config` file in the top-level directory
- [x] Add your custom profile to the `README.md` file in the top-level directory
- [x] Add your profile name to the `profile:` scope in `.github/workflows/main.yml`

### CODE REVIEW

**Comment by davidecarlson** [comment]
I just realized I had a bunch of intermediate files from a test run that was accidentally performed in the configs directory.  Will clean those out and push the changes back to my branch.

**Comment by davidecarlson** [comment]
Okay, my extraneous files have been removed, only the intended changes now exist on my branch.

**Comment by jfy133** [comment]
Sorry @davidecarlson didn't see this was stuck on 'first time contributor - approve and run', running now

**Comment by davidecarlson** [comment]
Thanks, @jfy133!

It looks like there were formatting issues on my config's documentation file.  I've run `prettier` to hopefully fix them and pushed the changes.  

Do you mind running the checks again?

Thanks!
Dave

**Review by jfy133 — APPROVED** [review]

**Comment by davidecarlson** [comment]
Possibly dumb question - is there anything else that _I_ need to do before this PR is merged?
Thanks!
Dave

**Comment by jfy133** [comment]
Nope, sorry forgot you might not be able to merge as a first time contributor 🤦‍♀️.

Merging now!

**Pull request merged**
