### PR TITLE
account for gpu jobs in sanger

### PR DESCRIPTION
**Pull request by maxozo**
---
name: New Config
about: A new cluster config
---

Please follow these steps before submitting your PR:

- [x] If your PR is a work in progress, include `[WIP]` in its title
- [x] Your PR targets the `master` branch
- [x] You've included links to relevant issues, if any
- [x] Requested review from @nf-core/maintainers and/or #request-review on slack

Steps for adding a new config profile:

- [x] Add your custom config file to the `conf/` directory
- [x] Add your documentation file to the `docs/` directory
- [x] Add your custom profile to the `nfcore_custom.config` file in the top-level directory
- [x] Add your custom profile to the `README.md` file in the top-level directory
- [x] Add your profile name to the `profile:` scope in `.github/workflows/main.yml`

### CODE REVIEW

**Comment by priyanka-surana** [comment]
@maxozo It would be nice if someone from CellGen takes a look at this. They use GPUs extensively as well and it would be good to make sure this change does not break anything for them. I am going to add a few people from Sanger to review this.

**Comment by maxozo** [comment]
> @maxozo It would be nice if someone from CellGen takes a look at this. They use GPUs extensively as well and it would be good to make sure this change does not break anything for them. I am going to add a few people from Sanger to review this.

thanks, i dont think this should break anything, since i only added a tag for a gpu jobs.

**Comment by BioinfoTongLI** [comment]
Hi @priyanka-surana , looks good to me. This additional label won't affect us

**Review by muffato — COMMENTED** [review]
In my view, the sanger config should only be about translating Nextflow's memory, cpus, etc, parameters to Sanger LSF parameters (queue, clusterOptions). Increasing the memory at every attempt should be a decision made by each pipeline, not centrally.
Could you consider an hybrid of this and @BioinfoTongLI 's version (https://github.com/workflows-community/nf-core-configs/pull/2) where:

1. the queue is selected based on the runtime and `task.memory`,
2. `clusterOptions` sets both the memory and the GPU in `-M`, `-R 'select[]'`, and `-gpu`
3. Resets `memory` to prevent Nextflow adding another `-M... -R 'select[]'`

Then, in your pipeline, do something like
```
withLabel: gpu {
    memory = { check_max( 12.GB * task.attempt, 'memory' ) }
}
```

**Comment by maxozo** [comment]
> In my view, the sanger config should only be about translating Nextflow's memory, cpus, etc, parameters to Sanger LSF parameters (queue, clusterOptions). Increasing the memory at every attempt should be a decision made by each pipeline, not centrally. Could you consider an hybrid of this and @BioinfoTongLI 's version ([workflows-community#2](https://github.com/workflows-community/nf-core-configs/pull/2)) where:
> 
>     1. the queue is selected based on the runtime and `task.memory`,
> 
>     2. `clusterOptions` sets both the memory and the GPU in `-M`, `-R 'select[]'`, and `-gpu`
> 
>     3. Resets `memory` to prevent Nextflow adding another `-M... -R 'select[]'`
> 
> 
> Then, in your pipeline, do something like
> 
> ```
> withLabel: gpu {
>     memory = { check_max( 12.GB * task.attempt, 'memory' ) }
> }
> ```

Sounds good @muffato ! will give this a go.

**Comment by maxozo** [comment]
> > In my view, the sanger config should only be about translating Nextflow's memory, cpus, etc, parameters to Sanger LSF parameters (queue, clusterOptions). Increasing the memory at every attempt should be a decision made by each pipeline, not centrally. Could you consider an hybrid of this and @BioinfoTongLI 's version ([workflows-community#2](https://github.com/workflows-community/nf-core-configs/pull/2)) where:
> > ```
> > 1. the queue is selected based on the runtime and `task.memory`,
> > 
> > 2. `clusterOptions` sets both the memory and the GPU in `-M`, `-R 'select[]'`, and `-gpu`
> > 
> > 3. Resets `memory` to prevent Nextflow adding another `-M... -R 'select[]'`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then, in your pipeline, do something like
> > ```
> > withLabel: gpu {
> >     memory = { check_max( 12.GB * task.attempt, 'memory' ) }
> > }
> > ```
> 
> Sounds good @muffato ! will give this a go.

Hi @muffato @priyanka-surana @BioinfoTongLI  - how about this version, i think it works ok. Let me know if you got some extra suggestions?

**Review by muffato — COMMENTED** [review]
It looks more like what I would expect. I don't have any GPU job to test it, but if you / @BioinfoTongLI are happy, let's go for it.

I can't review the Leicester changes.

**Comment by maxozo** [comment]
> It looks more like what I would expect. I don't have any GPU job to test it, but if you / @BioinfoTongLI are happy, let's go for it.
> 
> I can't review the Leicester changes.

Cool, lets get it merger. I tested it on my gpu jobs and it works. I think @BioinfoTongLI was happy with the previous version so probs should be ok. 
Re the leicester, i am the only one using nextflow there so should its ok.

**Comment by ewels** [comment]
Hi all! Was it intentional to make changes to the `leicester` config profile? This looks like it might have been an accident.

**Comment by maxozo** [comment]
Hi, yes, this is intentional, thanks for checking Phil. I am part of both institutions and I am accounting for gpu jobs both in Sanger and Leicester to run gpu jobs. Sent from my iPhoneOn 24 Oct 2023, at 23:08, Phil Ewels ***@***.***> wrote:﻿
Hi all! Was it intentional to make changes to the leicester config profile? This looks like it might have been an accident.

**Review by priyanka-surana — APPROVED** [review]

**Comment by priyanka-surana** [comment]
We generally give everyone at least 1-2days to reply depending on the change before merging. Not everyone does development full time. That was the only hold up. All good now.

**Comment by maxozo** [comment]
> We only checked the Sanger profile. In general, we give everyone at least 1-2days to reply depending on the change before merging. Not everyone does development full time. That was the only hold up. All good now.

Thank you @priyanka-surana @ewels @BioinfoTongLI @muffato ! Also thanks for the help and suggestions. Much appreciated. :)

**Pull request merged**
