### PR TITLE
Update hasta.config

### PR DESCRIPTION
**Pull request by sofstam**
This PR updates the `hasta.config` by adding the process `KRAKENUNIQ_PRELOADEDKRAKENUNIQ`

### CODE REVIEW

**Review by LilyAnderssonLee — COMMENTED** [review]
Memory doesn't increase significantly, going from 72 to 80 GB. Is it necessary to increase it further?

**Comment by sofstam** [comment]
Do you suggest to leave it as it and skip this update or to increase it to to > 80GB?

**Comment by sofstam** [comment]
Yes, I got a memory error.

**Comment by jfy133** [comment]
@LilyAnderssonLee @sofstam did you make a decision in the end?

**Comment by sofstam** [comment]
We can close this for now and revisit once we start validating krakenuniq for our samples.

**Pull request closed without merging**
