### PR TITLE
Add hMPX_B1 to `viralrecon/genomes.config`

### PR DESCRIPTION
**Pull request by pcjentsch**
The `viralrecon` pipeline also works for assembling hMPX genomes. This PR adds paths to `genomes.config` for the `NC_063383.1` genome, pointing to data from nextclade that I have made a PR to add  into `nf-core/test-datasets` (cf nf-core/test-datasets#594). 

I have tested this config file successfully locally, and changed the paths such that this works when the aforementioned PR is merged.

Let me know if there are any changes I should make, thank you!

- [x] Your PR targets the master branch

Thanks to @fmaguire for his assistance on this.

### CODE REVIEW

**Comment by drpatelh** [comment]
Hi @pcjentsch ! Sorry, I just saw these PRs 👀 I added reference and annotation files downloaded from the NCBI in https://github.com/nf-core/configs/pull/403 and some info in the [README](https://github.com/nf-core/test-datasets/tree/viralrecon#nc_0633831)

Looking at this deeper it looks like there is a discrepancy in the reference names between NCBI and Nextclade 🤦🏽 

### Nextclade

```
$ nextclade dataset get --name 'hMPXV' --reference 'NC_063383.1' --tag '2022-08-19T12:00:00Z' --output-dir './nextclade_hMPXV_NC_063383.1_2022-08-19T12_00_00Z'

$ head -n 2 nextclade_hMPXV_NC_063383.1_2022-08-19T12_00_00Z/reference.fasta
>NC_063383.1 Monkeypox virus, complete genome
ATTTTACTATTTTATTTAGTGTCTAGAAAAAAATGTGTGACCCACGACCGTAGGAAACTCTAGAGGGTAA
```

### NCBI

```
$ wget -L https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/014/621/545/GCA_014621545.1_ASM1462154v1/GCA_014621545.1_ASM1462154v1_genomic.fna.gz

$ zcat GCA_014621545.1_ASM1462154v1_genomic.fna.gz | head -n 2
>MT903340.1 Monkeypox virus isolate MPXV-M5312_HM12_Rivers, complete genome
ATTTTACTATTTTATTTAGTGTCTAGAAAAAAATGTGTGACCCACGACCGTAGGAAACTCTAGAGGGTAAGAAAAATCAA
```

Which means we will have to use the Nextclade reference rather than the NCBI to deal with the mismatch in reference names. Or we manually rename the NCBI reference.

I am not up to scratch with the recommended references. Am I missing something here?

Similar command to download the latest `hMPXV_B1` with the naming convention used by the pipeline:

```
nextclade dataset get --name 'hMPXV_B1' --reference 'pseudo_ON563414' --tag '2022-08-19T12:00:00Z' --output-dir './nextclade_hMPXV_B1_pseudo_ON563414_2022-08-19T12_00_00Z'
```

**Comment by drpatelh** [comment]
Ok. It turned out that we were using the Genbank sftp instead of RefSeq sftp in NCBI website to download the `NC_063383.1` reference files. I have replaced them now and the reference name matches this Nextclade dataset:

```
$ nextclade dataset get --name 'hMPXV' --reference 'NC_063383.1' --tag '2022-08-19T12:00:00Z' --output-dir './nextclade_hMPXV_NC_063383.1_2022-08-19T12_00_00Z'
```

I have created a PR updating the config https://github.com/nf-core/configs/pull/405

Please can you check it looks good? cc @saramonzon or do I need to use another Nextclade dataset with this reference?

**Comment by saramonzon** [comment]
I think the reference don't need to match between for mapping/consensus and nextclade datasets, and they can be customized by the user so i think we can use the hMPXV dataset for NC_063383.1, which would be the safer option.

**Comment by drpatelh** [comment]
Thanks @saramonzon ! Yes, if the references don't need to match then we can be flexible with which Nextclade dataset we use as default. Especially, since we probably won't be changing the core dataset in the future. Happy to upload the best one.

The current options are these 3:

```
$ nextclade dataset list
Showing latest dataset(s) compatible with this version of Nextclade (2.4.0), having attributes: reference='default', tag='latest':
╭───────────────────────────┬──────────────────────────┬──────────────────────────┬──────────────────────────┬──────────────────────────╮
│ name                      │ reference                │ tag                      │ attributes               │ comment                  │
╞═══════════════════════════╪══════════════════════════╪══════════════════════════╪══════════════════════════╪══════════════════════════╡
│ MPXV                      │ ancestral (*)            │ 2022-08-19T12:00:00Z (*) │ name=MPXV                │ Updated clade names to   │
│ 'Monkeypox (All Clades)'  │ 'Reconstructed ancestral │                          │ reference=ancestral (*)  │ WHO announcement,        │
│                           │ MPXV'                    │                          │ tag=2022-08-19T12:00:00Z │ introduce outbreak level │
│                           │                          │                          │ (*)                      │                          │
├───────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┤
│ hMPXV                     │ NC_063383.1 (*)          │ 2022-08-19T12:00:00Z (*) │ name=hMPXV               │ Updated clade names to   │
│ 'Human Monkeypox (hMPXV)' │ 'MPXV-M5312_HM12_Rivers' │                          │ reference=NC_063383.1    │ WHO announcement,        │
│                           │                          │                          │ (*)                      │ introduce outbreak level │
│                           │                          │                          │ tag=2022-08-19T12:00:00Z │                          │
│                           │                          │                          │ (*)                      │                          │
├───────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┤
│ hMPXV_B1                  │ pseudo_ON563414 (*)      │ 2022-08-19T12:00:00Z (*) │ name=hMPXV_B1            │ Updated clade names to   │
│ 'Human Monkeypox Lineage  │ 'MPXV_USA_2022_MA001 in  │                          │ reference=pseudo_ON56341 │ WHO announcement,        │
│ B.1*'                     │ NC_063383 coordinates'   │                          │ 4 (*)                    │ introduce outbreak level │
│                           │                          │                          │ tag=2022-08-19T12:00:00Z │                          │
│                           │                          │                          │ (*)                      │                          │
├───────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┤
```

Let me know what you think.

**Comment by drpatelh** [comment]
Ok. I have gone for the Nextclade dataset specified here in https://github.com/nf-core/configs/pull/402#issuecomment-1225804115. Shout if you thing we need to change this.

Now added in https://github.com/nf-core/configs/pull/403 https://github.com/nf-core/configs/pull/405

**Pull request closed without merging**
