### PR TITLE
Remove prince config

### PR DESCRIPTION
**Pull request by genericdata**
---
name: Remove Prince config
about: Removal of a config of a retired cluster
---

The NYU Prince cluster was decommissioned on February 1st, 2021.
https://sites.google.com/nyu.edu/nyu-hpc/hpc-systems/retired-clusters#h.h5dd1cn9akn2

- [x] Remove your custom config file to the `conf/` directory
- [x] Remove your documentation file to the `docs/` directory
- [x] Remove your custom profile to the `nfcore_custom.config` file in the top-level directory
- [x] Remove your custom profile to the `README.md` file in the top-level directory
- [x] Remove your profile name to the `profile:` scope in `.github/workflows/main.yml`

### CODE REVIEW

**Review by jfy133 — APPROVED** [review]

**Comment by tobsecret** [comment]
Before we remove this, let me check whether the NYU Greene cluster can use the basically same configurations as prince did and we can recycle this config. I no longer work at NYU but I do know people are still using nextflow and maybe also nf-core.

**Comment by tobsecret** [comment]
Tagging @genericdata to verify whether these nf-core config files that were originally used for NYU Prince can be used with NYU Greene.
nf-core is a repository of ready-to-run nextflow workflows for biological data analysis and processing. It is useful for many menial biological processing tasks that were done frequently at CGSB during my time there - hence why I set up the config in the first place.

**Comment by genericdata** [comment]
I submitted another pull request as nyu_hpc as a more general listing. I guess I could have renamed everything and updated the original.

**Comment by tobsecret** [comment]
@genericdata Oh I am a dummy - totally didn't realize this was your PR, sorry it's my vacation brain.
no this is perfectly fine.

**Review by tobsecret — APPROVED** [review]

**Comment by maxulysse** [comment]
cf https://github.com/nf-core/configs/pull/607

**Pull request merged**
