### PR TITLE
A new profile for adcra [KMUTT]

### PR DESCRIPTION
**Pull request by kalayaneech**
---
name: adcra
about: A new cluster config
---

### CODE REVIEW

**Review by ameynert — COMMENTED** [review]
The failure of test 'Check if nextflow config runs in repository_root' is also happening for nf-core/configs master branch.

```
(base) [ameyner2@node2c15(eddie) nf-core]$ git clone git@github.com:nf-core/configs.git
Cloning into 'configs'...
Enter passphrase for key '/home/ameyner2/.ssh/id_ed25519': 
remote: Enumerating objects: 7076, done.
remote: Counting objects: 100% (116/116), done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 7076 (delta 59), reused 92 (delta 47), pack-reused 6960
Receiving objects: 100% (7076/7076), 1.41 MiB | 0 bytes/s, done.
Resolving deltas: 100% (4477/4477), done.
(base) [ameyner2@node2c15(eddie) nf-core]$ cd configs/
(base) [ameyner2@node2c15(eddie) configs]$ nextflow config -show-profiles .
NOTE: Nextflow is not tested with Java 1.8.0_66 -- It's recommended the use of version 11 up to 18

Unexpected error [StackOverflowError]
```

**Comment by ameynert** [comment]
Requesting a review from https://github.com/orgs/nf-core/teams/configs-team - see above comment about failing test.

**Comment by jfy133** [comment]
> Requesting a review from @nf-core/configs-team - see above comment about failing test.

Can be ignored! Bug in current stable version of NXF, should be fixed in the next release thus we keep it activated now!

**Comment by jfy133** [comment]
Ref: https://github.com/nextflow-io/nextflow/issues/2815

**Comment by ameynert** [comment]
> Ref: [nextflow-io/nextflow#2815](https://github.com/nextflow-io/nextflow/issues/2815)

Thanks @jfy133 ! Will approve now.

**Review by ameynert — APPROVED** [review]
Can ignore issue with -show-profiles.

**Comment by jfy133** [comment]
The other failures will hopefully be fixed with: https://github.com/nf-core/configs/pull/410

**Pull request merged**
