### PR TITLE
Update abims.md

### PR DESCRIPTION
**Pull request by lecorguille**
---
name: Update ABiMS documentation
about: Add some doc in the doc or simplify

### CODE REVIEW

**Review by maxulysse — APPROVED** [review]

**Comment by maxulysse** [comment]
What did we missed in #446?

**Comment by lecorguille** [comment]
Is there a render of the docs in this repo somewhere within the nf-core website?

**Comment by maxulysse** [comment]
Not at the moment, if I'm not mistaken, we've been thinking about it for a while, but we're now working on a new version of the website.

@mashehu is there any plan for the configs to be included soon(ish)?

**Comment by lecorguille** [comment]
Otherwise, this PR is "mergeable"

**Comment by mashehu** [comment]
> is there any plan for the configs to be included soon(ish)?

It will come with the new website later this year

**Comment by maxulysse** [comment]
Then let's merge it

**Pull request merged**
