### PR TITLE
Add Google Cloud Life Sciences config

### PR DESCRIPTION
**Pull request by evanfloden**
This PR adds support for the [Google Cloud Life Sciences](https://cloud.google.com/life-sciences/) to nf-core pipelines.

### CODE REVIEW

**Comment by apeltzer** [comment]
Markdown Linting complained a little ;-) 

Otherwise, this looks good to me? 

```
/home/runner/work/configs/configs/docs/google.md:5 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
/home/runner/work/configs/configs/docs/google.md:8 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
/home/runner/work/configs/configs/docs/google.md:9 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below] [Context: "## Quick Start"]
/home/runner/work/configs/configs/docs/google.md:10 MD031/blanks-around-fences Fenced code blocks should be surrounded by blank lines [Context: "```"]
/home/runner/work/configs/configs/docs/google.md:10 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"]
/home/runner/work/configs/configs/docs/google.md:16 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below] [Context: "### Required Parameters"]
/home/runner/work/configs/configs/docs/google.md:17 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Above] [Context: "#### `--google-bucket`"]
/home/runner/work/configs/configs/docs/google.md:20 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below] [Context: "### Optional Parameters"]
/home/runner/work/configs/configs/docs/google.md:21 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Above] [Context: "#### `--google-zone`"]
/home/runner/work/configs/configs/docs/google.md:24 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below] [Context: "#### `--google-preemptible`"]
/home/runner/work/configs/configs/docs/google.md:27 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below] [Context: "#### `--google-debug`"]
/home/runner/work/configs/configs/docs/google.md:30 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
/home/runner/work/configs/configs/docs/google.md:31 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below] [Context: "## Cloud Life Sciences Setup"]
/home/runner/work/configs/configs/docs/google.md:34 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
/home/runner/work/configs/configs/docs/google.md:35 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 3]
```

**Comment by evanfloden** [comment]
Thanks @apeltzer, linting is done! 

Just need permission to merge the GitHub workflows file.

**Comment by evanfloden** [comment]
I think something happened to the CCGA profile in between my PR and the test. May need some help from someone with permissions to merge it.

**Comment by apeltzer** [comment]
Aah, yeah that one was dropped in the meantime ;-)

**Comment by apeltzer** [comment]
Merging this to `merge-google` branch to get the CCGA one out :)

**Pull request merged**
