### PR TITLE
Attempt to fix process specific configs with pipeline specific configs

### PR DESCRIPTION
**Pull request by jfy133**
SHH specific EAGER config is inherited (as seen by description), but increased resources not inherited. Removal of check_max will fix this, however can't test without merging because igenomes error when using `--custom_config_base` from https://github.com/jfy133/configs getting an `igenomes error`

### CODE REVIEW

**Comment by MaxUlysse** [comment]
I think I might have found your problem.
It was in the eager pipeline:
https://github.com/nf-core/eager/blob/336340d9c5145e935e304bc3b7311b576817c7b3/nextflow.config#L194-L232

**Comment by jfy133** [comment]
Need to remove: `igenomes_base = "./iGenomes"` I guess? No idea why the boilerplate is there twice...

@apeltzer any idea why the base is there? Can we remove it?

**Comment by apeltzer** [comment]
Probably outdated stuff. We could remove at least one instance and also make sure that all of this is either used properly OR not at all. I'm kind of hoping to keep iGenomes support in EAGER, as it will make some things easier for people, e.g. pure newbies running the pipeline on system where the ydon't know how to put reference genomes somewhere :-)

**Comment by jfy133** [comment]
Wouldn't something like iGenomes need to be specified in a profile anyway? Rather than hardcoded?

**Comment by jfy133** [comment]
I've also removed the boilerplate redundency.

Doing so I saw  we have a parameter to ignore iGenomes (`--igenomesIgnore`), which I can use for testing of the shh eager-specific protocol. So that issue is now 'fixed'.

However I now get the report that the pipeline configs can't be loaded - but I get it twice?

```
Launching `/projects1/users/fellows/nextflow/eager2/institution_pipeline_config/eager/main.nf` [evil_golick] - revision: 829a77b4e5
WARNING: Could not load nf-core/config/eager profiles: https://raw.githubusercontent.com/jfy133/configs/master/pipeline/eager.config
WARN: It appears you have never run this project before -- Option `-resume` is ignored
WARNING: Could not load nf-core/config/eager profiles: https://raw.githubusercontent.com/jfy133/configs/master/pipeline/eager.config
WARN: It appears you have never run this project before -- Option `-resume` is ignored
```

[https://raw.githubusercontent.com/jfy133/configs/master/pipeline/eager.config](https://raw.githubusercontent.com/jfy133/configs/master/pipeline/eager.config) works though?

As does what that profile points to... [https://raw.githubusercontent.com/jfy133/configs/master/conf/pipeline/eager/shh.config](https://raw.githubusercontent.com/jfy133/configs/master/conf/pipeline/eager/shh.config)

Unless the `params.custom_base_config` isn't being passed all the way down? Any ideas @MaxUlysse 

---

Command 
```
nextflow run /projects1/users/fellows/nextflow/eager2/institution_pipeline_config/eager/ \
--custom_config_base https://raw.githubusercontent.com/jfy133/configs/master \
-profile shh,sdag \
--reads '/projects1/users/fellows/nextflow/eager2/mt_test_data/test-datasets/testdata/Mammoth/fastq/JK2*{R1,R2}*.fq.gz' \
--fasta '/projects1/users/fellows/nextflow/eager2/mt_test_data/test-datasets/reference/Mammoth/Mammoth_MT_Krause.fasta' \
--pairedEnd \
--run_bam_filtering \
--bam_discard_unmapped \
--bam_unmapped_type 'fastq' \
--run_metagenomic_screening \
--database "/projects1/users/fellows/nextflow/eager2/mt_test_data/test-datasets/databases/malt/" \
-with-tower \
--igenomesIgnore \
-resume
```

And the nextflow log:

```
Dec-06 12:54:16.924 [main] DEBUG nextflow.cli.Launcher - $> nextflow run /projects1/users/fellows/nextflow/eager2/institution_pipeline_config/eager/ --custom_config_base 'https://raw.githubusercontent.com/jfy133/configs/master' -profile shh,sdag --reads '/projects1/users/fellows/nextflow/eager2/mt_test_data/test-datasets/testdata/Mammoth/fastq/JK2*{R1,R2}*.fq.gz' --fasta /projects1/users/fellows/nextflow/eager2/mt_test_data/test-datasets/reference/Mammoth/Mammoth_MT_Krause.fasta --pairedEnd --run_bam_filtering --bam_discard_unmapped --bam_unmapped_type fastq --run_metagenomic_screening --database /projects1/users/fellows/nextflow/eager2/mt_test_data/test-datasets/databases/malt/ -with-tower --igenomesIgnore -resume
Dec-06 12:54:17.031 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 19.10.0
Dec-06 12:54:17.933 [main] INFO  nextflow.cli.CmdRun - Launching `/projects1/users/fellows/nextflow/eager2/institution_pipeline_config/eager/main.nf` [evil_golick] - revision: 829a77b4e5
Dec-06 12:54:17.952 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /projects1/users/fellows/nextflow/eager2/institution_pipeline_config/eager/nextflow.config
Dec-06 12:54:17.953 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /projects1/users/fellows/nextflow/eager2/institution_pipeline_config/eager/nextflow.config
Dec-06 12:54:17.961 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `shh,sdag`
Dec-06 12:54:18.936 [main] DEBUG nextflow.config.ConfigBuilder - Available config profiles: [sdag, uppmax_devel, denbi_qbic, test_fna, genotoul, bigpurple, test_pretrim, uppmax, test_bam, docker, gis, ccga, test_humanbam, conda, singularity, munin, prince, czbiohub_aws, hebbe, cfc, uzh, debug, test, genouest, cbe, ccga_dx, cdag, crick, czbiohub_aws_highpriority, kraken, phoenix, shh, awsbatch, pasteur, uct_hex, binac]
Dec-06 12:54:18.949 [main] WARN  nextflow.config.ConfigBuilder - It appears you have never run this project before -- Option `-resume` is ignored
Dec-06 12:54:19.007 [main] DEBUG nextflow.extension.OperatorEx - Dataflow extension methods: branch,buffer,chain,choice,collate,collect,collectFile,combine,concat,count,countBy,countFasta,countFastq,countLines,countText,cross,distinct,filter,first,flatMap,flatten,fork,groupBy,groupTuple,ifEmpty,into,join,last,map,max,mean,merge,min,mix,phase,print,println,randomSample,reduce,separate,set,splitCsv,splitFasta,splitFastq,splitText,spread,subscribe,sum,take,tap,toDouble,toFloat,toInteger,toList,toLong,toSortedList,transpose,unique,until,view
Dec-06 12:54:19.013 [main] DEBUG nextflow.Session - Session uuid: 8b30b3fa-38a2-44cd-8826-cb0ed6728ced
Dec-06 12:54:19.013 [main] DEBUG nextflow.Session - Run name: evil_golick
Dec-06 12:54:19.014 [main] DEBUG nextflow.Session - Executor pool size: 32
Dec-06 12:54:19.025 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /projects1/users/fellows/nextflow/eager2/institution_pipeline_config/eager/nextflow.config
Dec-06 12:54:19.025 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /projects1/users/fellows/nextflow/eager2/institution_pipeline_config/eager/nextflow.config
Dec-06 12:54:19.026 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `shh,sdag`
Dec-06 12:54:19.548 [main] DEBUG nextflow.config.ConfigBuilder - Available config profiles: [sdag, uppmax_devel, denbi_qbic, test_fna, genotoul, bigpurple, test_pretrim, uppmax, test_bam, docker, gis, ccga, test_humanbam, conda, singularity, munin, prince, czbiohub_aws, hebbe, cfc, uzh, debug, test, genouest, cbe, ccga_dx, cdag, crick, czbiohub_aws_highpriority, kraken, phoenix, shh, awsbatch, pasteur, uct_hex, binac]
Dec-06 12:54:19.549 [main] WARN  nextflow.config.ConfigBuilder - It appears you have never run this project before -- Option `-resume` is ignored
Dec-06 12:54:19.569 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 19.10.0 build 5170
  Created: 21-10-2019 15:07 UTC (17:07 CEST)
  System: Linux 4.4.0-38-generic
  Runtime: Groovy 2.5.8 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_74-b02
  Encoding: UTF-8 (UTF-8)
  Process: 43297@mpi-sdag1 [172.20.102.80]

```

**Comment by jfy133** [comment]
> Probably outdated stuff. We could remove at least one instance and also make sure that all of this is either used properly OR not at all. I'm kind of hoping to keep iGenomes support in EAGER, as it will make some things easier for people, e.g. pure newbies running the pipeline on system where the ydon't know how to put reference genomes somewhere :-)

 https://github.com/nf-core/eager/issues/312

**Comment by jfy133** [comment]
Actually @MaxUlysse the removal of check_max should fix this, as we discussed yesterday. Please double check and merge.

the custom_base_config is an EAGER issue and not suitable here. Will push that over to EAGER.

**Comment by MaxUlysse** [comment]
I'm so confused by your issues

**Comment by jfy133** [comment]
> I can't see anything wrong with the code, no idea why you have these issues or where they're coming from...

Me neither :cry:

**Pull request merged**
