### PR TITLE
Add dummy configs for all missing configs

### PR DESCRIPTION
**Pull request by jfy133**
This is for allowing us to uncomment out the part in the pipeline template.

I wonder if it just works 'as is' or if we have to add an explicit profile or not... ideas @maxulysse ?

### CODE REVIEW

**Review by maxulysse — APPROVED** [review]
LGTM, we just need to be sure we add any new pipeline

**Comment by mashehu** [comment]
One thing I find sub-optimal: we now have `conf/pipeline/` and `pipeline/`. too easy to confuse the two, imo

**Comment by maxulysse** [comment]
> One thing I find sub-optimal: we now have `conf/pipeline/` and `pipeline/`. too easy to confuse the two, imo

both have different usage, but I see your point

**Comment by mashehu** [comment]
yes, different usage and same name is never good

**Comment by jfy133** [comment]
> If you want I can write a github action which periodically checks https://nf-co.re/pipeline_names.json and creates that.

That would be _awesome_

**Comment by jfy133** [comment]
Should I wait for the GHA @mashehu before merging? But otherwise I will prepare the tools template to uncomment the relevant code, and update our new-project-guidance

**Comment by mashehu** [comment]
yes, let's add the GHA to this PR. Any chance we can use a different name than `pipeline/` for the placeholders?

**Comment by jfy133** [comment]
> yes, I will add the GHA to this PR. Any chance we can use a different name than `pipeline/` for the placeholders?

No I don't think so. It's already embedded in existing pipelines for a while, so if we changed it would break compatibility with old releases. @maxulysse correct me if I'm wrong

**Comment by mashehu** [comment]
okay, GHA is there. as usual need to really test it in production (I ran it locally with `act` and it looked fine, but we will see). Left some testing code in it, so we will need a clean-up PR after this one is merged and the workflow has been tested

**Comment by jfy133** [comment]
Looks good to me @mashehu ! 

If you can both review: https://github.com/nf-core/tools/pull/2936/ and re-review this one, then i will merge this PR and shortly after the tools one

**Review by mashehu — APPROVED** [review]

**Pull request merged**
