### PR TITLE
documentation on how to fix bianca "Requested node configuration is not available" problem

### PR DESCRIPTION
**Pull request by arontommi**
Bianca only allows 7 GB per core, so max_mem of 128 GB results in an "Requested node configuration is not available" error.

### CODE REVIEW

**Comment by MaxUlysse** [comment]
Hi @arontommi good spot.
Can't we get a fat node on bianca?
And just out of curiosity, which pipeline where you running?

**Comment by arontommi** [comment]
Thanks,
Yes you could request a fat node instead
I was running sarek (vc with strelka in this case )

**Comment by ewels** [comment]
There's already docs there about using fat nodes, so I'm happy with this. Thanks!

**Comment by ewels** [comment]
Tests are failing due to the missing `MENDEL` config, which was removed in #80. Not sure why though, I've retriggered them - maybe they will pass on the second attempt 🤔

**Comment by ewels** [comment]
Switched PR to be against the master branch.

**Comment by ewels** [comment]
Tests fixed 🎉

**Pull request merged**
