### PR TITLE
Update abims.config

### PR DESCRIPTION
**Pull request by lecorguille**
---
name: Config Update
about: Update the ABiMS Config
---

### CODE REVIEW

**Review by maxulysse — APPROVED** [review]

**Comment by lecorguille** [comment]
I'm trying to update our profile but I'm not sure about the usage of the singularity cache dir for the user point-of-view.

For example, I downloaded some singularity images:
```bash
 export NXF_SINGULARITY_CACHEDIR=/shared/software/singularity/images/nf-core/
nf-core download --container singularity -p 2 --singularity-cache-only rnaseq
```

I got plenty of files ans directories:
```
depot.galaxyproject.org-singularity-bbmap-39.01--h5c4e2a8_0.img
depot.galaxyproject.org-singularity-bedtools-2.30.0--hc088bd4_0.img
[...]
depot.galaxyproject.org-singularity-ucsc-bedgraphtobigwig-377--h446ed27_1.img
depot.galaxyproject.org-singularity-umi_tools-1.1.2--py38h4a8c8d9_0.img
nf-core-rnaseq-3.10.1
```

How the end-user with be able to use those images with this kind of command:
```
nextflow run nf-core/rnaseq-3.10.1 -profile abims --outdir
```

I'm sorry, I'm not a nextflow user myself. So my apologies for the naive questions

**Comment by maxulysse** [comment]
@lecorguille there are no stupid questions.
https://github.com/nf-core/configs/pull/446/files#diff-88274fda08b5e6ba68c31d34af939342bc39195264447a04a492a6507ccef400R12

should make it so that nextflow knows where are the images.

What's in `nf-core-rnaseq-3.10.1/`?

**Comment by lecorguille** [comment]
> should make it so that nextflow knows where are the images.

How the user will specify the version of the wf?

> What's in nf-core-rnaseq-3.10.1/?

```
$ tree -L 2 nf-core-rnaseq-3.10.1
nf-core-rnaseq-3.10.1
├── configs
│   ├── bin
│   ├── CITATION.cff
│   ├── conf
│   ├── configtest.nf
│   ├── docs
│   ├── LICENSE
│   ├── nextflow.config
│   ├── nfcore_custom.config
│   ├── pipeline
│   └── README.md
└── workflow
    ├── assets
    ├── bin
    ├── CHANGELOG.md
    ├── CITATIONS.md
    ├── CODE_OF_CONDUCT.md
    ├── conf
    ├── docs
    ├── lib
    ├── LICENSE
    ├── main.nf
    ├── modules
    ├── modules.json
    ├── nextflow.config
    ├── nextflow_schema.json
    ├── pyproject.toml
    ├── README.md
    ├── subworkflows
    ├── tower.yml
    └── workflows
```
This directory have been created by the cmd `nf-core download --container singularity -p 2 --singularity-cache-only rnaseq`

**Comment by maxulysse** [comment]
> How the user will specify the version of the wf?

All images should be there, so -r should do the trick there to specify workflow version.

> This directory have been created by the cmd nf-core download --container singularity -p 2 --singularity-cache-only rnaseq

That's the pipeline + configuration, more useful when you're on an offline setting

**Comment by lecorguille** [comment]
@maxulysse  thanks for your responses.
I still have some doubt but we can keep in touch if you don't mind if my user have difficulties.

Let merge this 👍

**Pull request merged**
