### PR TITLE
awsbatch config update

### PR DESCRIPTION
**Pull request by ggabernet**
- Updates to allow pipelines resume when running on AWS batch.

### CODE REVIEW

**Review by ewels — APPROVED** [review]
LGTM 🚀

**Comment by ewels** [comment]
x-ref https://github.com/nextflow-io/nextflow/issues/813#issuecomment-724124512

Note that this new feature presumably isn't released yet. I'm not sure if adding this config before it's generally available will break stuff?

**Comment by ggabernet** [comment]
yes, that's right. We wait for the next Nextflow release before merging 👍

**Comment by ewels** [comment]
Maybe worth also adding the minimum nextflow version to this config? Or perhaps that can only be put in the main pipeline? Not sure..

**Review by apeltzer — APPROVED** [review]
I wondered why there is no issue open about this, but I've only opened one internally here to fix this 😆 Good catch!

**Comment by ewels** [comment]
Happy to merge this now that the edge release is out (and we are requiring that for many pipelines / Tower always runs it etc).

**Pull request merged**
