### PR TITLE
adding Estonian Biocentre cluster profile

### PR DESCRIPTION
**Pull request by marcel-keller**
Adding the Estonian Biocentre (https://genomics.ut.ee/en/about-us/estonian-biocentre) cluster profile.

### CODE REVIEW

**Comment by MaxUlysse** [comment]
Duplicate of #133 
@marcel-keller which one do you want to keep?

**Comment by jfy133** [comment]
> Duplicate of #133
> @marcel-keller which one do you want to keep?

Github went wierd. I'm guiding Marcel through the process!

**Comment by jfy133** [comment]
@MaxUlysse is there anything doc's wise that is missing?

**Comment by MaxUlysse** [comment]
I think it looks good

**Comment by drpatelh** [comment]
@marcel-keller @jfy133 forgot to add a link for this profile to the main `README.md` here:
https://github.com/nf-core/configs#documentation

**Pull request merged**
