### PR TITLE
update daisybio profile: use group of the launch directory for work directory

### PR DESCRIPTION
**Pull request by JohannesKersting**
---
name: daisybio profile update
about: use group of the launch directory for work directory
---

Our profile creates all work directories in a centralized location. Currently, this work directory will belong to the group of the user launching the pipeline. As a consequence, only this user will be able to use Nextflow's resume feature.

This update sets the group of the work directory (and group special permission) to the group of the launch directory to allow all users in a shared group project to access the work directory and use the resume feature.

Please follow these steps before submitting your PR:

- [ ] If your PR is a work in progress, include `[WIP]` in its title
- [x] Your PR targets the `master` branch
- [ ] You've included links to relevant issues, if any

Steps for adding a new config profile:

- [ ] Add your custom config file to the `conf/` directory
- [ ] Add your documentation file to the `docs/` directory
- [ ] Add your custom profile to the `nfcore_custom.config` file in the top-level directory
- [ ] Add your custom profile to the `README.md` file in the top-level directory
- [ ] Add your profile name to the `profile:` scope in `.github/workflows/main.yml`
- [ ] OPTIONAL: Add your custom profile path and GitHub user name to `.github/CODEOWNERS` (`**/<custom-profile>** @<github-username>`)

### CODE REVIEW

**Review by nictru — APPROVED** [review]
Much needed :D

**Comment by JohannesKersting** [comment]
Do I need to be worried about the failed github actions?
Don't think they relate to the change in this pull request.

**Comment by nictru** [comment]
The issue is that the actions are trying to utilize the latest nextflow `24.11-edge`, which requires Java 17 or later, but somehow the environment sticks to Java 11

**Comment by nictru** [comment]
@maxulysse is working on a repo-wide fix similar to [this](https://github.com/nf-core/references/pull/50)

**Comment by maxulysse** [comment]
> @maxulysse is working on a repo-wide fix similar to [this](https://github.com/nf-core/references/pull/50)

https://github.com/nf-core/configs/pull/813

**Pull request merged**
