### PR TITLE
adding vsc_kul_uhasselt configs

### PR DESCRIPTION
**Pull request by Joon-Klaps**
---
name: vsc_kul_uhasselt
about: A new cluster config for the KULeuven and Uhasselt Tier2 clusters Genius and Wice
---
The VSC (Flemish supercomputer) has multiple clusters which are specific to flemish universities.
I propose not to extend the `vsc_ugent.config` file but instead make a new config `vsc_kul_uhasselt.config` as some of the prefixed variables like `$VSC_SCRATCH_VO_USER` are not available on KUL's and UHasselt's HPC. 

Please follow these steps before submitting your PR:

- [X] Your PR targets the `master` branch

Steps for adding a new config profile:

- [X] Add your custom config file to the `conf/` directory
- [X] Add your documentation file to the `docs/` directory
- [X] Add your custom profile to the `nfcore_custom.config` file in the top-level directory
- [X] Add your custom profile to the `README.md` file in the top-level directory
- [X] Add your profile name to the `profile:` scope in `.github/workflows/main.yml`

### CODE REVIEW

**Comment by Joon-Klaps** [comment]
The Genius and Wice clusters are currently under maintenance so they haven't been tested yet

**Comment by nvnieuwk** [comment]
There are only two clusters on both HPCs? The config looks good to me!

**Comment by Joon-Klaps** [comment]
> There are only two clusters on both HPCs? The config looks good to me!

You're right there is one more the [`Superdome`](https://docs.vscentrum.be/en/latest/leuven/tier2_hardware/superdome_hardware.html) which is part of the Genius cluster.

**Comment by Joon-Klaps** [comment]
I figured out what was wrong, the important difference between vsc_ugent and vsc_kul_uhasselt is that it requires a credential account. 
I tested all 3 configurations and tested with resume, all were successful.

**Review by nvnieuwk — APPROVED** [review]
LGTM! Did you manage to run a full run with this config?

**Pull request merged**
