### PR TITLE
vsc_ugent: limit queuesize

### PR DESCRIPTION
**Pull request by matthdsm**
Update vsc_ugent config to limit queueSize, so we stop getting slurm controller timeouts

### CODE REVIEW

**Review by nvnieuwk — APPROVED** [review]
Fingers crossed this will work :crossed_fingers:

**Comment by matthdsm** [comment]
It does, I'm using it right now 😛

**Comment by nvnieuwk** [comment]
It always works at first (it can be a bit sneaky)

**Comment by matthdsm** [comment]
@nf-core/configs-team, how do we fix the failing CI? Or do we just ignore it?

**Comment by nvnieuwk** [comment]
It's a known error with Nextflow, nothing we can do anything about for now
It should be fixed in the next Nextflow version

**Comment by matthdsm** [comment]
allright, merging! If it breaks anything I blame @nvnieuwk!

**Pull request merged**
