### PR TITLE
Update cluster specification vsc_kul_uhasselt

### PR DESCRIPTION
**Pull request by Joon-Klaps**
Only in the wice profile the specific cluster was specified and not on genius and superdome profiles

- [X] If your PR is a work in progress, include `[WIP]` in its title
- [X] Your PR targets the `master` branch
- [X] You've included links to relevant issues, if any
- [x] Requested review from @nf-core/maintainers and/or #request-review on slack

### CODE REVIEW

**Comment by Joon-Klaps** [comment]
* it used to work as default cluster was genius but they updated and now require a cluster specification

**Review by maxulysse — APPROVED** [review]
LGTM

**Comment by pontus** [comment]
Are you certain this works as intended? My memory says `clusterOptions` is not used when checking for active jobs, so it will lose track of them and think they've gone astray.

**Comment by Joon-Klaps** [comment]
I've been using this modified version the last few days and it worked as I hoped for. I recall having issues even before the update if the billing account wasn't specified with `--account=${params.project}"`.  I don't know if there are better solutions to do this?

**Comment by pontus** [comment]
Then I'm curious, does `squeue` work as expected without specifying the cluster?

**Comment by Joon-Klaps** [comment]
Don't have any jobs running but think yes...
```
✔ [Jul/14 12:50] @tier2-p-login-1 ~/data $ squeue
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
✔ [Jul/14 12:52]@tier2-p-login-1 ~/data $ squeue --clusters=wice
CLUSTER: wice
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
✔ [Jul/14 12:52] @tier2-p-login-1 ~/data $ squeue --clusters=genius
CLUSTER: genius
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
```

Info on sbatch
```
[Jul/14 12:49] @tier2-p-login-1 ~/data $ sbatch --help
...
-M, --clusters=names        Comma separated list of clusters to issue
                              commands to.  Default is current cluster.
                              Name of 'all' will submit to run on all clusters.
                              NOTE: SlurmDBD must up.
...
```

**Comment by Joon-Klaps** [comment]
Just double checked, if cluster options not specified: 
```
Error executing process > 'NFCORE_VIRALRECON:ILLUMINA:PREPARE_GENOME:BLAST_MAKEBLASTDB (nCoV-2019.reference.fasta)'

Caused by:
  Failed to submit process to grid scheduler for execution

Command executed:

  sbatch .command.run

Command exit status:
  1

Command output:
  sbatch: lua: Please select a cluster for your job via the -M/--cluster option
  sbatch: error: cli_filter plugin terminated with error
```
the `.command.run` looks as followed:
```
#!/bin/bash
#SBATCH -J nf-NFCORE_VIRALRECON_ILLUMINA_PREPARE_GENOME_BLAST_MAKEBLASTDB_(nCoV-2019.reference.fasta)
#SBATCH -o /scratch/leuven//work/a7/5712cd4b93e2d08e955c56ee4e358a/.command.log
#SBATCH --no-requeue
#SBATCH --signal B:USR2@30
#SBATCH -c 36
#SBATCH -t 48:00:00
#SBATCH --mem 221184M
#SBATCH -p bigmem
NXF_CHDIR=/scratch/leuven/work/a7/5712cd4b93e2d08e955c56ee4e358a
# NEXTFLOW TASK: NFCORE_VIRALRECON:ILLUMINA:PREPARE_GENOME:BLAST_MAKEBLASTDB (nCoV-2019.reference.fasta)
...
```
Whereas one of my previous runs with the cluster options:
```
#!/bin/bash
#SBATCH -J nf-NFCORE_VIRALRECON_ILLUMINA_FASTQ_TRIM_FASTP_FASTQC_FASTP_(LVE00040)
#SBATCH -o /scratch/leuven/work/e8/6bb668fec90ad5ce95a708a9789ccf/.command.log
#SBATCH --no-requeue
#SBATCH --signal B:USR2@30
#SBATCH -c 6
#SBATCH -t 08:00:00
#SBATCH --mem 36864M
#SBATCH -p batch
#SBATCH --cluster genius --account=lp_phylogeo_inf_gpu
NXF_CHDIR=/scratch/leuven/work/e8/6bb668fec90ad5ce95a708a9789ccf
# NEXTFLOW TASK: NFCORE_VIRALRECON:ILLUMINA:FASTQ_TRIM_FASTP_FASTQC:FASTP (LVE00040)
....
```
So `clusterOptions` definetly still gets used in my case. 
```
nf-core, version 2.7.2
N E X T F L O W
      version 23.04.2 build 5870
      created 08-06-2023 08:29 UTC 
```

**Comment by pontus** [comment]
Ah, okay, it was broken on purpose for submitting only, then I see.

Yes, for submitting, `clusterOptions` is used, just not later on when looking for jobs.

**Pull request merged**
